baseURL = 'https://kmatejak.github.io/krisblog/'
languageCode = 'en-us'
title = 'Kris dev blog'

paginate = 3

[params]
    favicon = "krisblog/static/images/favicon.ico"
    dateformat = "Jan 2, 2006"
    description = "The fastest blog"

[taxonomies]
    category = "categories"
    author = "authors"